export const storedMushrooms = [
  "agaricus-macrosporus",
  "blushing-wood-mushroom",
  "field",
  "grey-spotted-amanita",
  "horse",
  "medusa",
  "orange-grisette",
  "pavement",
  "prince",
  "spring-fieldcap",
  "tawny-grisette",
  "the-great-wood-mushroom",
  "wood-mushroom",
];
