import { Button, Flex, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import { useUser } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Mushine learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction={"column"} justifyContent="center" align="center" mt={10}>
        <Heading as={"h1"} p={5} textAlign="center">
          Welcome to Mush-ine learning! 🍄
        </Heading>

        {!user.user && (
          <>
            <Text color="red.400">Not signed in</Text>
            <Link href="/api/auth/login">
              <Button m={2}>Log in</Button>
            </Link>
          </>
        )}
        {user.user && (
          <>
            <Text color="green.400">Signed in as: {user.user?.name}</Text>
            <Link href="/api/auth/logout">
              <Button m={2}>Log out</Button>
            </Link>
          </>
        )}
        <Image
          src="/shroomschool.png"
          alt="mushroom"
          width={200}
          height={200}
        />

        <Flex
          direction={"column"}
          justifyContent="center"
          align="center"
          mt={5}
        >
          <Link href="/bank">
            <Button m={2}>Go to Mushroom bank</Button>
          </Link>

          <Link href="/forage">
            <Button m={2}>Go to Mushroom Forage Quiz</Button>
          </Link>
        </Flex>
      </Flex>
    </>
  );
};

export default Home;
