import { Button, Flex, Heading, Icon } from "@chakra-ui/react";
import { BiUser } from "react-icons/bi";
import { CiVault } from "react-icons/ci";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import AuthStatus from "./components/AuthStatus";
import { TopLevelWrapper } from "./components/TopLvlWrapper";

const Home: NextPage = () => {
  return (
    <TopLevelWrapper backgroundColor="#F2E1C3">
      <Head>
        <title>Mushine learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction={"column"} justifyContent="center" align="center">
        <Heading
          as={"h1"}
          p={5}
          textAlign="center"
          size="4xl"
          fontFamily="honeyMushroom"
          letterSpacing="wide"
          color="#172b56"
        >
          Mush-ine learning! 🍄
        </Heading>

        <AuthStatus />

        <Image
          src="/shroomschool.png"
          alt="mushroom"
          width={200}
          height={200}
          className="wave"
        />

        <Flex
          direction={"column"}
          justifyContent="center"
          align="center"
          mt={5}
        >
          <Link href="/profile">
            <Button
              m={2}
              color={"white"}
              backgroundColor={"#543034"}
              _hover={{ color: "black", backgroundColor: "gray.100" }}
            >
              Profile
              <Icon as={BiUser} ml={2} />
            </Button>
          </Link>

          <Link href="/bank">
            <Button
              m={2}
              color={"white"}
              backgroundColor={"#543034"}
              _hover={{ color: "black", backgroundColor: "gray.100" }}
            >
              Mushroom bank
              <Icon as={CiVault} ml={2} />
            </Button>
          </Link>

          <Heading size="md" pt={5}>
            Games
          </Heading>
          <Flex>
            <Link href="/forage">
              <Button
                m={2}
                color={"white"}
                backgroundColor={"#0C6279"}
                _hover={{ color: "black", backgroundColor: "gray.100" }}
              >
                Forage Game
              </Button>
            </Link>

            <Link href="/multi">
              <Button
                m={2}
                color={"white"}
                backgroundColor={"#0C6279"}
                _hover={{ color: "black", backgroundColor: "gray.100" }}
              >
                MultiChoice Game
              </Button>
            </Link>

            <Link href="/tile">
              <Button
                m={2}
                color={"white"}
                backgroundColor={"#0C6279"}
                _hover={{ color: "black", backgroundColor: "gray.100" }}
              >
                Tile Game
              </Button>
            </Link>
          </Flex>
        </Flex>
      </Flex>
    </TopLevelWrapper>
  );
};

export default Home;
