import { Button, Flex, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction={"column"} justifyContent="center" align="center" mt={10}>
        <Heading as={"h1"} p={5} textAlign="center">
          Log in
        </Heading>

        <Link href="/api/auth/login">
          <Button m={2}>Log in</Button>
        </Link>
      </Flex>
    </>
  );
};

export default Home;
