name: Run vitest unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CLOUD_NAME: ${{secrets.CLOUD_NAME}}
  CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
  AUTH0_SECRET: ${{secrets.AUTH0_SECRET}}
  AUTH0_BASE_URL: ${{secrets.AUTH0_BASE_URL}}
  AUTH0_ISSUER_BASE_URL: ${{secrets.AUTH0_ISSUER_BASE_URL}}
  AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
  AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
  VITE_cloud_name: ${{secrets.VITE_cloud_name}}
  VITE_api_key: ${{secrets.VITE_api_key}}
  VITE_api_secret: ${{secrets.VITE_api_secret}}
  TEST_USERNAME: ${{secrets.TEST_USERNAME}}
  TEST_SUB: ${{secrets.TEST_SUB}}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        env:
          LOCAL_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - run: yarn ci
      - run: yarn run build
      - run: yarn test
